name: ğŸš€ Deploy developer dashboard on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: cwp.salescode.dev
          username: app
          password: "L0jad0ec0mmerce*"
          server-dir: api_transcrever/

      - name: ğŸ“‚ SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: cwp.salescode.dev
          username: root
          password: "Wsbws8g5@ts"
          script: |
            cd /home/app/api_transcrever
            
            # Criar diretÃ³rio de logs se nÃ£o existir
            mkdir -p logs
            
            # Atualizar o arquivo de serviÃ§o systemd
            sudo cp api-transcrever.service /etc/systemd/system/api-transcrever.service
            sudo systemctl daemon-reload
            
            # Ativar ambiente virtual e atualizar dependÃªncias
            source venv/bin/activate
            pip install -r requirements.txt --upgrade
            
            # Reiniciar o serviÃ§o
            sudo systemctl restart api-transcrever
            
            # Verificar status
            sudo systemctl status api-transcrever --no-pager


      
      